{% set name = "fast_matrix_market" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fast-matrix-market-{{ version }}.tar.gz
  sha256: 72e2223b9b23cd34962c21e3b018746e9a0d9f0dde91e166b6af949f9527d06f

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make     # [not win]
    - ninja    # [win]
    - python
  host:
    - python
    - scikit-build-core
    - pybind11
    - pip
  run:
    - python
    - libstdcxx-ng  # [linux]
    - libcxx        # [osx]

test:
  imports:
    - fast_matrix_market
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest
    - scipy
  source_files:
    - tests/


about:
  home: https://github.com/alugowski/fast_matrix_market
  summary: Fast and full-featured Matrix Market file I/O
  license: BSD-2-Clause
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - alugowski
