{% set name = "fast_matrix_market" %}
{% set version = "1.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fast-matrix-market-{{ version }}.tar.gz
  sha256: 578745f0784f4dc8e123bf931e53fdebe77feb897cc3f87f86a1a8162fa418ba

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - scikit-build-core
    - pybind11
    - pip
  run:
    - python
    - libstdcxx-ng  # [linux]
    - libcxx  # [osx]

test:
  imports:
    - fast_matrix_market
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest
    - scipy
  source_files:
    - tests/


about:
  home: https://github.com/alugowski/fast_matrix_market
  summary: Fast and full-featured Matrix Market file I/O
  license: BSD-2-Clause
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - alugowski
